=== BackupTheBerlios/beautyj/src/de/gulden/application/beautyj/application.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    AMODA Application Description v 0.5

    Document type describing concepts used by the AMODA application framework
    and its implementing ApplicationEnvironments.
    
    The content gets parsed once during startup of an AMODA application by the
    application's ApplicationEnvironment or ApplicationEnvironmentFactory.
    According to the descriptions in this file, instances of application
    members are then instantiated which are used by the application at
    runtime.
    
    XML files of this document type are typically created by software
    developers as part of the internal source code of a project. The contents
    are usually not to be edited by the end user. As a consequence of this,
    it is recommended to distribute an AMODA application description file
    together with compiled .class files inside an application's .jar code
    archive and let the ApplicationEnvironment access it as a resource from
    the classpath. The default location used by the AMODA
    ApplicationEnvironment implementations is a file called 'application.xml'
    inside the same Java package as the project Application class (this is the
    class extending a subclass of GenericApplication or directly implementing 
    the model interface de.gulden.framework.amoda.model.Application).
    
    This DTD is provided for manual validation during development of the
    AMODA application. By default, an ApplicationEnvironment's implementation
    will not validate the XML using the DTD when initializing the application.
    
    This is licensed under the GNU Public License. See file README.TXT for
    details.
    
    Copyright (c) Jens Gulden 2002, amoda@jensgulden.de
    
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT application (metadata?,options?,members?)>
<!ATTLIST application
    version CDATA #REQUIRED
  >

<!-- Langstring - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!-- By encapsulating language dependant strings into tag <langstring
     lang="..">, AMODA is prepared for internationalization. It is up to
     the ApplicationEnvironment's implementations how to handle multiple
     languages.                                                           -->
<!ELEMENT langstring (#PCDATA)>
<!ATTLIST langstring
    lang CDATA #IMPLIED
  >

<!-- Metadata - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  
<!ELEMENT metadata (title|name|longname|version|author|description|license|license-message)*> <!-- single occurrence of each element only, but in free order -->

<!ELEMENT title (langstring)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT longname (langstring)*>
<!ELEMENT version (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT copyright (langstring)*>
<!ELEMENT description (langstring)*>
<!ELEMENT license (#PCDATA)>
<!ELEMENT license-message (langstring)*>

<!-- Options - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  
<!ELEMENT options (option|options-group)*>

<!ELEMENT option (type|default-value|description)*> <!-- single occurrence of each element only, but in free order -->
<!ATTLIST option
    id ID #REQUIRED
  >

<!ELEMENT options-group (option)*>
<!ATTLIST options-group
    id ID #REQUIRED
  >

<!-- Type of the option, this must match a fully qualified Java class, 
     e.g. java.io.File. Default is java.lang.String.                       -->
<!ELEMENT type (#PCDATA)>

<!ELEMENT default-value (#PCDATA)>
  
<!-- Members - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  
<!ELEMENT members (command|message)*>

<!ELEMENT command EMPTY>
<!ATTLIST command
    id ID #REQUIRED
    code CDATA #IMPLIED
  >

<!ELEMENT message (title?,text)>
<!ATTLIST message
    id ID #REQUIRED
  >

<!ELEMENT text (langstring)*>

=== BackupTheBerlios/beautyj/src/de/gulden/application/beautyj/application.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE application SYSTEM "application.dtd">

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- beautyJ 1.0                                                   -->
<!--                                                               -->
<!-- AMODA application descripiton                                 -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    
<application format-version="0.1"
             batch-mode="no"
             persistent-options="no">
             
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Metadata                                                  -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    
    <metadata>
        <name>BeautyJ</name>
        <version>1.0</version>
        <title>
            <langstring>BeautyJ</langstring>
        </title>
        <description>
            <langstring>A Java source code beautifier.</langstring>
        </description>
        <author>Jens Gulden</author>
        <email>beautyj@jensgulden.de</email>
        <license>GPL</license>
        <license-message>
            <langstring>This software comes with no warranty, please see file license.txt.</langstring>
        </license-message>
    </metadata>
    
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Options                                                   -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    
    <options>
        <option id="d">
            <!-- REQUIRED -->
            <description>
                <langstring>The directory to output the beautified sources to.</langstring>
            </description>
        </option>
        <option id="sourclet">
            <description>
                <langstring>Full class name of the Sourclet to be used for generating beautified class files.</langstring>
            </description>
            <default-value>
                de.gulden.util.javasource.sourclet.standard.StandardSourclet
            </default-value>
        </option>
        <option id="project.name">
            <description>
                <langstring>The project's name.</langstring>
            </description>
        </option>
        <option id="project.version">
            <description>
                <langstring>The project's version number.</langstring>
            </description>
        </option>
        <option id="project.date">
            <description>
                <langstring>The project's date.</langstring>
            </description>
            <default-value>
                today
            </default-value>
        </option>
        <option id="project.description">
            <description>
                <langstring>Short description of the project.</langstring>
            </description>
        </option>
        <option id="project.headerfile">
            <description>
                <langstring>A text file to insert as header comment (instead of auto-building a header with project and author information).</langstring>
            </description>
        </option>
        <option id="author.name">
            <description>
                <langstring>The author's name.</langstring>
            </description>
        </option>
        <option id="author.email">
            <description>
                <langstring>The author's email address.</langstring>
            </description>
        </option>

        <!-- doc.class - - - - - - - - - - - - - -->
        <options-group id="doc.class.description">
            <option id="doc.class.description.remove.dummy">
                <type>boolean</type>
                <description>
                    <langstring>Remove dummy description from a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.description.remove.empty">
                <type>boolean</type>
                <description>
                    <langstring>Remove empty description from a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.description.remove.text">
                <type>boolean</type>
                <description>
                    <langstring>Remove any description from a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.description.create.dummy">
                <type>boolean</type>
                <description>
                    <langstring>Create dummy description for a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.description.create.text">
                <type>boolean</type>
                <description>
                    <langstring>Create auto-text description for a class's javadoc comment.</langstring>
                </description>
            </option>
        </options-group>
        <options-group id="doc.class.author">
            <option id="doc.class.author.remove.dummy">
                <type>boolean</type>
                <description>
                    <langstring>Remove dummy @author tag from a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.author.remove.empty">
                <type>boolean</type>
                <description>
                    <langstring>Remove empty @author tag from a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.author.remove.text">
                <type>boolean</type>
                <description>
                    <langstring>Remove @author tag from a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.author.create.dummy">
                <type>boolean</type>
                <description>
                    <langstring>Create dummy @author tag for a class's javadoc comment (can be removed in subsequent runs using ...remove.dummy).</langstring>
                </description>
            </option>
            <option id="doc.class.author.create.text">
                <type>boolean</type>
                <description>
                    <langstring>Create @author tag for a class's javadoc comment with the author name set by option -author.name.</langstring>
                </description>
            </option>
        </options-group>
        <options-group id="doc.class.version">
            <option id="doc.class.version.remove.dummy">
                <type>boolean</type>
                <description>
                    <langstring>Remove dummy text from a class's @version tag in the javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.version.remove.empty">
                <type>boolean</type>
                <description>
                    <langstring>Remove empty @version tag from a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.version.remove.text">
                <type>boolean</type>
                <description>
                    <langstring>Remove @version tag from a class's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.class.version.create.dummy">
                <type>boolean</type>
                <description>
                    <langstring>Create @version tag for a class's javadoc comment with dummy entry (can be removed in subsequent runs using ...remove.dummy).</langstring>
                </description>
            </option>
            <option id="doc.class.version.create.text">
                <type>boolean</type>
                <description>
                    <langstring>Create @version tag for a class's javadoc comment with the version set by option -version.</langstring>
                </description>
            </option>
        </options-group>

        <!-- doc.method - - - - - - - - - - - - - -->
        <options-group id="doc.method.description">
            <option id="doc.method.description.remove.dummy">
                <type>boolean</type>
                <description>
                    <langstring>Remove dummy description from a method's or constructor's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.method.description.remove.empty">
                <type>boolean</type>
                <description>
                    <langstring>Remove empty description from a method's or constructor's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.method.description.remove.text">
                <type>boolean</type>
                <description>
                    <langstring>Remove any description from a method's or constructor's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.method.description.create.dummy">
                <type>boolean</type>
                <description>
                    <langstring>Create dummy description for a method's or constructor's javadoc comment.</langstring>
                </description>
            </option>
            <option id="doc.method.description.create.text">
                <type>boolean</type>
                <description>
                    <langstring>Create auto-text description for a method's or constructor's javadoc comment.</langstring>
                </description>
            </option>
        </options-group>
        <options-group id="doc.method.param">
            <option id="doc.method.param.remove.dummy">
                <type>boolean</type>
